CREATE TABLE public.tools (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title varchar(50) NOT NULL,
	link varchar(50) NOT NULL,
	description varchar(120) NOT NULL,
	tags _varchar NOT NULL
);
CREATE UNIQUE INDEX tools_title_idx ON public.tools USING btree (title);


CREATE TABLE public.users (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	username varchar(50) NOT NULL,
	email varchar(60) NOT NULL,
	"password" varchar(120) NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (id)
);
CREATE UNIQUE INDEX users_email_idx ON public.users USING btree (email);
CREATE UNIQUE INDEX users_username_idx ON public.users USING btree (username);