version: "3.8"

services:

  postgres:
    image: postgres
    container_name: postgres_tool
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql